version: '3'
services:
  javaapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - CONN=jdbc:postgresql://postgressvc:5432/postgres?user=postgres&password=testdb
      # - POSTGRES_HOST=postgressvc
      # - POSTGRES_PASSWORD=postgres
      # - POSTGRES_USER=testdb
    depends_on:
      - postgressvc
  postgressvc:
    image: postgres
    # ports:
    #   - '5432:5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  
